### ISSUE TITLE
Expose Headers Location

### ISSUE THREAD

**Issue by hugoalexmartins** [nelmio/NelmioCorsBundle#105]
Hi,

I've been follow this tutorial:
https://codereviewvideos.com/course/symfony-3-with-reactjs-and-angular/video/simple-symfony-3-restful-api-setup 

To integrate FOS REST with Angular, backend with frontend.
Just **don't** installed the **APIdoc** bundle

A have a post action, which save and object and after, return a redirect view to get that object. The fos rest bundle responses in the header a key Location (when I am doing by curl -verbose I see this key), but using restangular I didn't get any content from header...

This is my configuration:

```yaml
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ["Location"] # this being the important line
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']
```

I am doing anything wrong ?

Thanks in advance.
