### ISSUE TITLE
Headers not being sent

### ISSUE THREAD

**Issue by Wardevour** [nelmio/NelmioCorsBundle#117]
I'm using Symfony 4.2.2 and installed with the command: `composer req cors`

My config looks like:
```yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~
```

```
// env var
CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$
```

But I can't verify the headers are being sent for route https://localhost/api/inventories/.
These are what Firefox says are sent:
```
// Response
Cache-Control: max-age=0, must-revalidate, private
Connection: Keep-Alive
Content-Length: 49
Content-Type: application/json
Date: Sun, 03 Feb 2019 13:49:57 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.37 (Win64) OpenSSL/1.1.1a PHP/7.2.13
X-Powered-By: PHP/7.2.13

// Request
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cache-Control: max-age=0
Connection: keep-alive
Host: localhost
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
```

Am I forgetting a step or doing something wrong?
