### ISSUE TITLE
nelmio_cors and varnish

### ISSUE THREAD

**Issue by grekpg** [nelmio/NelmioCorsBundle#123]
```
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*'] dont work with varnish - it set first domain
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~
```

I use varnish cache - when open cachable api request on first domain - i get in response headers

Accept-Ranges: bytes
Access-Control-Allow-Origin: http://app.local
Access-Control-Expose-Headers: link
Age: 12
Cache-Control: public
Connection: keep-alive
Content-Length: 6722
Content-Type: application/json
Date: Thu, 21 Mar 2019 12:09:28 GMT
Expires: Fri, 22 Mar 2019 00:00:00 GMT
Server: nginx/1.10.3 (Ubuntu) 

so varnish save this header , when i open this page from other domain - have 
....as been blocked by CORS policy: The 'Access-Control-Allow-Origin'...

NelmioCorsBundle - return refferer page ? when i have * ?
