### ISSUE TITLE
Configuration ignored

### ISSUE THREAD

**Issue by geri777** [nelmio/NelmioCorsBundle#134]
I have placed my Yaml file in config/packages/nelmio_cors.yaml

Whatever I do - it's just ignored. For example, I need 
`allow_headers: ['Content-Type', 'Authorization']`
but all I get in the server response is 
`Access-Control-Allow-Headers: x-custom-auth`
which is the default value.

The server returns "Unauthorized header authorization"
I have already tried for hours - what might be my fault?

Here is my config/packages/nelmio_cors.yaml

```
nelmio_cors:
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
```

I have verified ...

- file permissions
- file encoding, hidden Characters, etc. (tested Utf-8 and Ansi)
- no tabs in the file, just spaces
