### ISSUE TITLE
Request in firefox returns access-control-allow-origin: null

### ISSUE THREAD

**Issue by sv-db** [nelmio/NelmioCorsBundle#135]
I've got a pretty much default setup.
```
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://localhost:8080']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['content-type', 'Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
```
When i make a request from Chrome, the headers are set as expected:

```
access-control-allow-headers: content-type, content-type, authorization
access-control-allow-methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
access-control-allow-origin: https://localhost:8080
access-control-max-age: 3600
```

But when I make the exact same request from Firefox, the following headers are return:
```
access-control-allow-headers: content-type, content-type, authorization
access-control-allow-methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
access-control-allow-origin: null
access-control-max-age: 3600
```
How can the result for allow-origin be null in this case?
