### ISSUE TITLE
Missing link header 

### ISSUE THREAD

**Issue by pesseyjulien** [nelmio/NelmioCorsBundle#152]
Hi,

I'm trying to use the React Admin from Api Platform but my response is missing the 'link' header.

My nemlio config : 

```
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/*':
            origin_regex: true
            allow_origin: ['%env(cors_allow_origin)%']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
            allow_headers: ['content-type', 'authorization']
            expose_headers: ['link']
            max_age: 3600
```

Request : https://dev.myworks.fr/docs.jsonld

Reponse headers :

```
HTTP/1.1 200 OK
Date: Wed, 22 Apr 2020 08:04:16 GMT
Server: Apache
X-Powered-By: PHP/7.2.1
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: deny
Cache-Control: no-cache, private
X-Debug-Token: 6137a8
X-Debug-Token-Link: https://dev.myworks.fr/_profiler/6137a8
X-Robots-Tag: noindex
Content-Length: 117523
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/ld+json; charset=utf-8
```

What I'm missing ?

Thanls in advance for your help !
