### ISSUE TITLE
Depdendency Injection for Configuration ['^/api/'] defaulting to allow_origin *

### ISSUE THREAD

**Issue by gleeflowers** [nelmio/NelmioCorsBundle#153]
Not sure if this is an issue or just my configuration, but basically this nelmio_cor yaml:

nelmio_cors:
  defaults:
    allow_credentials: false
    origin_regex: true
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/':
        origin_regex: true
        allow_origin: ['^https://blah.com']

Has a allow_origin * being injected at runtime in addition to the blah.com path., enabling all origin requests to make a request to /api/

Is this intended?  Seems like I am forced to create a different api semantic path in order to bypass this dependency injection. 

Can anyone help?

**Comment by fyrye** [comment]
I am not able to reproduce the issue you are experiencing. Do you have an `.htaccess` that may be overriding it?
Can you post the browser response headers?

A couple issues with your current configuration that may be complicating things.

- In your `allow_origin` regex pattern. the dot `.` is not escaped and the end boundary `$` is not specified
  - `allow_origin: [ '^https://blah\.com$' ]`
- You should add a base path `'^/'` config after your `'^/api/'` path config, to ensure false positives are not propagated.
```yaml
nelmio_cors:
  defaults:
    allow_credentials: false
    origin_regex: true
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ 'Content-Type', 'Authorization' ]
    expose_headers: [ 'Link' ]
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: [ '^https://blah\.com$' ]
    '^/': null
```
