### ISSUE TITLE
Controller action gets executed for invalid origins

### ISSUE THREAD

**Issue by shagenbrock** [nelmio/NelmioCorsBundle#157]
Hi,

we have an issue with https post requests in chrome that controller actions beeing executed even if the origin is rejected.

Q | A
--- | ---
Affected Bundle Versions | ^1.3.2, ^2
Affected Symfony Versions | checked with ^2.8, ^4.4
Affected Browsers | Chrome (86.0.4240.111), Safari (Version 14.0 (15610.1.28.1.9, 15610))
Not Affected | Firefox (81.0.2)

Example CORS configuration for a symfony application under "api.example.com"

```yml
nelmio_cors:
    paths:
        '^/api/':
            allow_origin:
              - 'https://valid-origin-host.example.com'
            allow_headers: ['Content-Type', ...]
```

Under a seperate domain (e.g.: https://invalid-origin-host.example.com) we have a file with following content:

```html
<html>
<head>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script><script>
$( document ).ready(function() {
    $.ajax({
        url: "https://api.example.com/api/example-endpoint",
        method: "POST",
        xhrFields: {withCredentials: true},
        data: {"title":"example payload"},
        crossDomain: true
    });
});
</script>
</head>
<body>
</body>
</html>
```

If you open the script you will see a invalid cors message in the browser console and the response of the endpoint would not be accessible for the javascript. Nevertheless the main controller action gets executed on the server as the request is not stopped with invalid origins.

Note: There was a forced response in this case that got removed in version 1.3.2.
