### ISSUE TITLE
XMLHttpRequest fail when server returns 302

### ISSUE THREAD

**Issue by pleerock** [nelmio/NelmioCorsBundle#17]
I get requests fail when I try to authorize (authorization redirects to /success or /fail)

**Chrome console gives me:**
XMLHttpRequest cannot load  `/web/app_dev.php/user/authorization` The request was redirected to `/web/app_dev.php/login/fail`, which is disallowed for cross-origin requests that require preflight. 

Here is my config:

``` yaml

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/':
            allow_origin: ['http://server.dev', 'http://localhost', 'http://127.0.0.1']
            allow_headers: ['Origin', 'Content-Type', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ['*']
            max_age: 3600

```
