### ISSUE TITLE
ERR_ABORTED 500 Response to preflight request doesn't pass access control check: It does not have HTTP ok status

### ISSUE THREAD

**Issue by Sophoniie** [nelmio/NelmioCorsBundle#195]
My nelmio_cors.yaml:
nelmio_cors:
```yaml
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET','POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS' ]
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_credentials: true
        max_age: 3600
    paths:
      '^/api/':
          allow_origin: [*]
          allow_headers: ['*'],
          allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
          max_age: 3600
          hosts: ['^api\.']
```
my server host address : `http://localhost:8000` and my origin address : `http://localhost:5174`
I got this error : 
`https://localhost:5174/#/:1 Access to fetch at 'http://localhost:8000/api/auth/me' from origin 'http://localhost:5174' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`
I don't know how to solve it I have clear cache so much time but nothing change.
Someone has already have this issue how to solve it ?

**Comment by YgorAlves** [comment]
I got the same issue, did you found any solution?

**Comment by easybi-vv** [comment]
Same issue, but only in Chrome and Chromium based browsers. Reverting to version 2.4 fixed this issue.

**Comment by tom-schmitz** [comment]
For me the issue was caused by a different listener inside the project. I managed to find the issue by using a tool like Insomnia or Postman to recreate the preflight options request generated by the browser. Using the browser dev tools, i copied the headers of the preflight call and put them into Insomnia, from there i got the same 500 error, but with an unreadably response body, disabling the `Accept-Encoding` header made the content readable, and thus allowing me to see the actual issue causing the preflight 500 error. (note run Symfony in dev mode to see the error).

**Nelmio cors config:**
```yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
```

**With default headers generated by the browser**
<img width="1246" height="381" alt="Image" src="https://github.com/user-attachments/assets/84875821-b4ef-4a8a-8dca-23894e1c8a70" />

**With `Accept-Encoding` disabled**
<img width="1790" height="430" alt="Image" src="https://github.com/user-attachments/assets/bf644e22-3b68-4f78-8431-b48b306249c4" />

**After implementing a fix in the LocaleListener**
<img width="1300" height="376" alt="Image" src="https://github.com/user-attachments/assets/cf35f915-d73f-402f-b4c1-c6e464ca0ef7" />


**Header generated by browser for the preflight OPTIONS request:**
```
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Connection: keep-alive
Host: localhost
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
```
