### ISSUE TITLE
How to inject logger into CorsListener?

### ISSUE THREAD

**Issue by fwm** [nelmio/NelmioCorsBundle#198]
The following doesn't work, neither many of its variations do:

```
Nelmio\CorsBundle\EventListener\CorsListener:
  class: Nelmio\CorsBundle\EventListener\CorsListener
  arguments:
    $logger: '@monolog.logger'
```

The second argument is just isn't passed to the CorsListener consrtuctor (in a compiled container)
