### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains the invalid value 'null'.

### ISSUE THREAD

**Issue by bichotll** [nelmio/NelmioCorsBundle#26]
Im using jQuery to connect to the api.

Chrome is throwing this message:

```
XMLHttpRequest cannot load http://localhost/wharever/web/app_dev.php/api/wharever-admin/v1/user/csrf. The 'Access-Control-Allow-Origin' header contains the invalid value 'null'. Origin 'http://localhost:9000' is therefore not allowed access.
```

The config.yml:

```
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/api/wharever-admin/':
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
```

The bundle works because when I delete the paths array I'm getting the following error:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. 
```

Weird behavior.
