### ISSUE TITLE
“405 method not allowed”. It's allright sending the request from a HTTP simulation web

### ISSUE THREAD

**Issue by Ziiweb** [nelmio/NelmioCorsBundle#30]
Im getting a 405 when sending a POST request to "http://www.sermobi.com/customers" from a mobille app using an ajax function.

But I don't get that error using a tool like http://www.hurl.it/#top.

I have already enable CORS on my server and checked that it works ok for GET requests. I have also enabled it for POST requests. At my `app/config.yml:`

```
nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
```

I have already checked the access log and this is what I get after the POST request:

```
www.sermobi.com:80 81.35.17.182 - - [24/Jul/2014:18:44:38 +0200] "POST /new HTTP/1.1" 405 1009 "-" "Mozilla/5.0 (Linux; Android 4.4.3; One S Build/KTU84M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36"
```

Any help?
