### ISSUE TITLE
Origin not validated correctly for GET requests

### ISSUE THREAD

**Issue by jsheth7** [nelmio/NelmioCorsBundle#34]
Hello,

I have the following configuration, with a standard Symfony 2.5 installation:

```
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://example.com']
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/':
            allow_origin: ['http://example.com']
            allow_headers: []
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
```

I am making a GET request using curl, with a different domain (http://boo.com) as the origin. The request is allowed, by the presence of the following header in the response:

```
Access-Control-Allow-Origin: http://boo.com
```

Here's the curl command I used:
    curl -H "Origin: http://boo.com" --verbose http://symfony25.local/app_dev.php

From looking through the code, I see that the origin check is only performed for pre-flight requests. But pre-flight requests are only sent by browsers with PUT and DELETE requests, and not with GET and POST requests (see: http://stackoverflow.com/questions/15381105/cors-what-is-the-motivation-behind-introducing-preflight-requests).

In CorsListener.php, within the onKernelResponse() function, I see the following line:

```
$response->headers->set('Access-Control-Allow-Origin', $request->headers->get('Origin'));
```

In this case, it's simply echo'ing back the Origin specified by the client, instead of validating it against the list of valid origins in the configuration file.

The only origin check happens within the checkOrigin() function, but this function is only called when the OPTIONS header is sent (for pre-flight requests).

Please let me know if I'm missing something in the configuration, or doing something wrong. But from the looks of it, this appears to be a serious bug. As a side note, this same behavior probably applies to POST requests as well, although I haven't tested that yet.

Finally, I tried removing "GET" from the list of allow_methods in the configuration file, but this did not prevent the same "Access-Control-Allow-Origin: http://boo.com" header from being sent back.
