### ISSUE TITLE
Getting 400 Bad Request on OPTIONS request

### ISSUE THREAD

**Issue by zabojad** [nelmio/NelmioCorsBundle#37]
Hi !

I'm trying to use NelmioCors along with the fos rest bundle.

For now, I'm just doing basic tests like posting data from a different domain than the api one. But doing so, I'm getting HTTP 400 errors on the OPTIONS requests.

Here is my NelmioCors config:
```
nelmio_cors:
    paths:
        '^/':
            allow_credentials: false
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 1728000
```

And here is what I have in Chrome debug console:
```
Remote Address:127.0.0.1:80
Request URL:http://127.0.0.1/tests/app_dev.php/api/v1/customers
Request Method:OPTIONS
Status Code:400 Bad Request

Request Headers
 Accept:*/*
 Accept-Encoding:gzip, deflate, sdch
 Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,pl;q=0.2
 Access-Control-Request-Headers:content-type
 Access-Control-Request-Method:POST
 Connection:keep-alive
 Host:127.0.0.1
 Origin:http://0.0.0.0:9000
 Referer:http://0.0.0.0:9000/
 User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/39.0.2171.95 Safari/537.36

Response Headers
 Access-Control-Allow-Methods:POST, PUT, GET, DELETE, OPTIONS
 Access-Control-Allow-Origin:http://0.0.0.0:9000
 Access-Control-Max-Age:1728000
 Cache-Control:no-cache
 Connection:close
 Content-Type:text/html; charset=UTF-8
 Date:Thu, 15 Jan 2015 18:33:36 GMT
 Server:Apache/2.4.9 (Unix) PHP/5.5.14
 Transfer-Encoding:chunked
 X-Debug-Token:c9e4ff
 X-Powered-By:PHP/5.5.14
```

What am I doing wrong ? Should NelmioCors manage the OPTIONS request or should I do something specific for this ?
