### ISSUE TITLE
Caching OPTIONS requests

### ISSUE THREAD

**Issue by gmajoulet** [nelmio/NelmioCorsBundle#39]
Hello,

Thanks for your bundle, it works like a charm.
I'm able to send cross origin requests, but it's sending an ````OPTIONS```` request before every other call. I'd like to cache those, I guess that's what the ````max_age```` option is meant for.

I think this was supposed work, here is the config I'm using:

````
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Api-Key', 'Origin', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
````

Am I missing something?
Thanks!
