### ISSUE TITLE
he 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost', but only one is allowed. 

### ISSUE THREAD

**Issue by antonioperic** [nelmio/NelmioCorsBundle#40]
XMLHttpRequest cannot load http://liveboard-dev.locastic.com/api/v1/login. The 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost', but only one is allowed. Origin 'http://localhost' is therefore not allowed access.

```
nelmio_cors:
paths:
    '^/api/':
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        max_age: 3600
```
