### ISSUE TITLE
use along with HTTP cache

### ISSUE THREAD

**Issue by zabojad** [nelmio/NelmioCorsBundle#42]
Hi ! 

I'm using the NelmioCorsBundle along with FosRestBundle and [HTTP caching](http://symfony.com/doc/2.3/book/http_cache.html).

In one of my REST enpoint, I'm doing this:

```
            $response = $this->handleView($this->view($ret, 200));

            $response->setPublic();
            $response->setMaxAge(21600);
            $response->setSharedMaxAge(21600);
            $response->headers->addCacheControlDirective('must-revalidate', true);

            return $response;
```

In that case, the CORS header aren't set on the response. What am I missing ?

Note that it is working fine if I'm not http caching the response...

Also, here is my NelmioCors config:

```
nelmio_cors:
    paths:
        '^/':
            allow_credentials: false
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 1728000
```
