### ISSUE TITLE
405 Error on OPTION request

### ISSUE THREAD

**Issue by alexander-schranz** [nelmio/NelmioCorsBundle#44]
Do I need to add something special to get the OPTIONS Request to work correctly currently I get an 405 Error Method not allowed.

My current test config is:

``` yml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        # '^/api/':
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            max_age: 3600
```

Here the response:

![error405onrequest](https://cloud.githubusercontent.com/assets/1698337/6946939/eb2dabec-d8a3-11e4-8b16-2c560d1ad9ad.png)

Here my router:debug where you see the requested route is allowed for POST:

![bildschirmfoto 2015-04-01 um 19 21 06](https://cloud.githubusercontent.com/assets/1698337/6947013/77bcac7a-d8a4-11e4-96c5-8ae8fcf2af90.png)
