### ISSUE TITLE
custom headers

### ISSUE THREAD

**Issue by Merk87** [nelmio/NelmioCorsBundle#49]
Hi.

I'm having a problem trying to pass custom headers to the config and I'm not sure what the hell I'm doing wrong.

In my API I need to recieve always two headers for calculating the security hash, lets say secret1 and secret2, when I go to the config of CORS and I set in the config I do like this:

``` yaml
 paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['secret1, secret2']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
```

Just Like I was doing in the VHost config

```
Header set Access-Control-Allow-Headers "secret1, secret2"
```

But when I set the config like I pasted, I have 200 status, but I don't receive the data, any idea?

**Comment by Seldaek** [comment]
allow_headers is an array, you should use `['secret1', 'secret2']` not all in one string.

**Comment by Merk87** [comment]
@Seldaek yep I tried that way too, and nothing...

**Comment by Seldaek** [comment]
is your browser doing an OPTIONS and then XXX request? Do you see that in the inspector and see what gets returned? I am pretty sure the bundle does its job.. You don't need to allow OPTIONS in allow_methods by the way unless you actually expect OPTIONS requests that aren't the pre-flight request.

**Comment by Merk87** [comment]
I'm expection OPTIONS headers, because the calls are done by an ionic build app

With this CORSBundle config 
```'^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'secretClient', 'secretHash']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600```
I got this response
```Access-Control-Allow-Origin:null
Cache-Control:no-cache
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Tue, 23 Jun 2015 12:44:49 GMT
Server:Apache/2.2.22 (Ubuntu)
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Powered-By:PHP/5.4.17-1~precise+1```

**Comment by Seldaek** [comment]
Access-Control-Allow-Origin:null seems to indicate a problem or maybe 
the request came without Origin header?

**Comment by Merk87** [comment]
Could be... If I set in the Vhost config file
```
Header set Access-Control-Allow-Headers "secret1, secret2"
Header set Access-Allow-Origin: '*'
```

starts to work with no problems at all...

**Comment by flexy1994** [comment]
I have the same problem.
I am using Dunglas API Bundle.

If allow_origin ist set to '*' i get an 405 Methode Not Allowed.

The response header Access-Control-Allow-Origin contains the same as request header.

**Comment by blaues0cke** [comment]
As a "more symfony like" workaround than editing your vhost config you may want to add this in your `app_dev.php` before the `$response` is sent:

    $response->headers->set('Access-Control-Allow-Origin', '*');

**Comment by Merk87** [comment]
@blaues0cke well is more or less the same, and also, add to dev environment has no so much sense...

**Comment by afilina** [comment]
Maybe this can help someone...

I had a local config where I added `hosts: ['^api\.']` but then when I put online on a different domain I was getting `Access-Control-Allow-Origin:null`. The solution was to remove the hosts part of the config.

**Comment by bigfoot90** [comment]
Same problem, I was missing ```origin_regex```

here is my working configuration:
```yml
nelmio_cors:
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['*']
            max_age: 3600
```
