### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Yunyun548** [nelmio/NelmioCorsBundle#63]
My Symfony API, I used FOSRestBundle worked ok and suddently I have a CORS error on every request form my Vue.js frontend

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rvpfront.dev:8080' is therefore not allowed access.

My Nelmio Configuration is the following

```
# Nelmio Cors Bundle
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['origin', 'content-type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
```

I'm really confused, it worked on friday and for 3 weeks before that.
