### ISSUE TITLE
Bad response headers for preflight OPTIONS requests

### ISSUE THREAD

**Issue by claborier** [nelmio/NelmioCorsBundle#71]
Hi, 

I'm bulding an app on top of ezplatform & symfony and I'm currently trying to use the JS REST API provided by ezplatform. 

Here are my nelmio_cors configs : 
```
nelmio_cors:
    paths:
        '^/api/ezp/v2/':
            max_age: 3600
            allow_credentials: true
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            expose_headers: []
```
Trying to request my app from an other domain (cors requests) I'm stuck with this error which occurs during preflight requests. 
`Response for preflight has invalid HTTP status code 405` (from Google Chrome)

Looking at the response headers, I noted that the response headers were not the ones I was hoping for. At least, this header is missing : 
`Access-Control-Allow-Methods: POST, PUT, GET, DELETE, OPTIONS`

Looking inside the nelmio_cors bundle code, I figured out that [this code form CorsListener](https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L111) is never reached : 
```
if ($options['allow_methods']) {
      $response->headers->set('Access-Control-Allow-Methods', implode(', ', $options['allow_methods']));
}
```

It seems that `$options` is empty or at least doesn't contains the good values.

I don't know if there is a bug here or if I' missing something. I also posted [this question on stackoverflow](http://stackoverflow.com/questions/41126474/ezplatform-symfony-rest-api-response-for-preflight-has-invalid-http-status) (for more detail)

Thanks in advance for help
