### ISSUE TITLE
Symfony 4 - NelmioCorsBundle doesn't return any error.

### ISSUE THREAD

**Issue by kgasienica** [nelmio/NelmioCorsBundle#83]
I have some troubles with using NelmioCorsBundle in my Symfony 4 project. 
Config:
```
nelmio_cors:
    paths:
      '^/api':
          allow_credentials: false
          allow_origin: ['http://www.example.com']
          allow_headers: ['*']
          allow_methods: ['GET','POST','DELETE','PUT']
          expose_headers: ['*']
          max_age: 3600
```
Request headers:
```
content-type: application/json
origin: http://www.x.com
access-control-request-method: GET
```
Response headers:
```
server:nginx/1.13.5
content-type:application/json
transfer-encoding:chunked
connection:keep-alive
x-powered-by:PHP/7.1.10
cache-control:no-cache, private
date:Mon, 30 Oct 2017 09:09:21 GMT
allow:GET
```
And full response body, while there should be an error that origin is not same.

I'm also wondering, why other params aren't checked? Like Access-Control-Allow-Credentials, Access-Control-Allow-Methods. I'm asking because in `Nelmio\CorsBundle\EventListener` you have function `getPreflightResponse` which checks it all only if OPTION Method header is set. What about other methods?
