### ISSUE TITLE
XMLHttpRequest cannot load, Origin not allowed

### ISSUE THREAD

**Issue by PierrickMartos** [nelmio/NelmioCorsBundle#9]
Hi,

First, thanks for this wonderful bundle. I've got a problem when using it on my project, i have this error : 

XMLHttpRequest cannot load http://www.website1.com/public-api/v1/tag/stat. Origin http://www.website2.com is not allowed by Access-Control-Allow-Origin. 

My config.yml : 

``` yml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
        allow_methods: ['POST','GET','DELETE','PUT']
        expose_headers: ['*']
        max_age: 0
    paths:
      '^/public-api':
          allow_credentials: true
          allow_origin: ['*']
          allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
          allow_methods: ['POST','GET','DELETE','PUT']
          expose_headers: ['*']
          max_age: 0
```

I try '^/public-api' or '^/public-api/', same error.

I also try to enable the bundle on the root with this config, it's work : 

``` yml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
        allow_methods: ['POST','GET','DELETE','PUT']
        expose_headers: ['*']
        max_age: 0
    paths:
      '^/': ~
```

I don't want to enable it on the entire project, how can i do ? Thanks.
