### ISSUE TITLE
Unable to set multiple origins via environment variable

### ISSUE THREAD

**Issue by frak** [nelmio/NelmioCorsBundle#92]
I am trying to set more than one origin and I would ideally like to do this with environment variables to make it easy to change origins in different environments. However I am unaware of any way to define an environment variable as an array, and if I define an array looking string `['host1.com', 'host2.com']` then I get the error:

   [Symfony\Component\Config\Definition\Exception\InvalidTypeException]
    Invalid type for path "nelmio_cors.paths.^/.allow_origin". Expected array, but got string

I am more than happy to have a go at fixing this but was wondering what the best approach would be?

**Comment by frankdejonge** [comment]
@frak .env vars are strings only. If you need multiple, simply add more .env vars.

**Comment by frak** [comment]
@frankdejonge thank you for your reply. If I understand you correctly, you are suggesting that I define a new env var for each CORS origin that I want to allow? The problem is that if I then want to add another CORS origin in a specific environment then I will need to change the code to add that parameter, and then provide a value for it across all environments.  Or have I misunderstood?

I currently have the following config:
```
nelmio_cors:
    paths:
        '^/':
            allow_credentials: true
            allow_origin: ['%cors_origin%']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
```
Are you suggesting I add another parameter as follows?
```
nelmio_cors:
    paths:
        '^/':
            allow_credentials: true
            allow_origin: ['%cors_origin%', '%extra_cors_origin%']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
```
Also, what value could I use in environments that do not need an extra CORS origin?

Sorry if I am being dumb, I appreciate your time is precious.
