### ISSUE TITLE
Response for preflight is invalid (redirect)

### ISSUE THREAD

**Issue by jdessaint** [nelmio/NelmioCorsBundle#97]
I have a front end in Angular 5 with which I call my backend in Symfony 3.4.8. I make an HTTP request in my Angular part for my server. For that, I made an HttpInterceptor like this :

```
intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    req = req.clone({headers: req.headers.append('Access-Control-Allow-Origin', '*')});
    req = req.clone({headers: req.headers.append('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Access-Control-Allow-Origin')});
    req = req.clone({headers: req.headers.append('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT,DELETE')});
    req = req.clone({headers: req.headers.append('Access-Control-Allow-Credentials', 'true')});
    req = req.clone({headers: req.headers.append('Content-Type', 'application/json')});
    return next.handle(req).do((event: HttpEvent<any>) => {
       ....
    }).catch(response => {
       ....
      }
    });
}
```

I send it to my server which must redirect me to another page (so I need a new Http request). But The server can't redirect me because I have the following error :

> Failed to load http://ipaddress:port/xxxxx: Response for preflight is invalid (redirect)

Here is my CORS configuration on my server :
```
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: ['*']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '/*':
            origin_regex: false
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
```
Anybody knows why I have this error and how I can correct it ? Thank You
